### PR TITLE
Arduino firmware to allow access to Alvik's sensors and actuators via ROS 2 topics and Micro-ROS

### PR DESCRIPTION
**Pull request by aentinger**

### CODE REVIEW

**Comment by aentinger** [comment]
The firmware currently enables tele-operation via `geometry_msgs/Twist` messages and will step-by-step extended to expose all of Alvik's sensors and actuators via ROS2 topics.

**Comment by gbr1** [comment]
@aentinger could you also open a PR on arduino-microros for the ESP32S3 support? Thx! <3

**Comment by gbr1** [comment]
@aentinger please to be compliant with actual OpenRobotics brand identity use "ROS 2 "instead of "ROS2" inside comments, titles, etc. thank you

**Comment by aentinger** [comment]
This PR requires https://github.com/micro-ROS/micro_ros_arduino/pull/1795 .

**Pull request merged**
