### PR TITLE
Fix: Arduino_Alvik::drive() not working due to function parameter not being used.

### PR DESCRIPTION
**Pull request by aentinger**
There was an additional bug concerning erroneous unit conversion.

### CODE REVIEW

**Comment by gbr1** [comment]
Hi @aentinger thank you for your fix! Please make this merge into devel, so it will added to next library update :D

**Review by gbr1 — COMMENTED** [review]
It looks ok to me :D

**Comment by aentinger** [comment]
Why into `devel` (It's 5 commits behind `main` at this very moment)? Latest working code per definition is usually in `main`. I'll merge into `main`, feel free to merge `main` into `devel` (or rebase `devel` onto `main`).

**Comment by gbr1** [comment]
@aentinger now release is different to main :D
We are preparing a new release with other implementations

**Pull request merged**
